EmployeeWebsite/Pages/CEO.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MediaBazar.BusinessLogic.Interfaces;
using MediaBazar.BusinessLogic.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeWebsite.Pages
{
	public class CEOModel : PageModel
	{
		public string ChartData { get; set; }

		public List<string> Categories { get; set; }

		public ItemStatsDto Electronics { get; set; }

        public ItemStatsDto Furniture { get; set; }

        public ItemStatsDto Gaming { get; set; }

        public ItemStatsDto Kitchen { get; set; }

        public ItemStatsDto Office_Supplies { get; set; }

        public ItemStatsDto Sports_outdoors { get; set; }

        public ItemStatsDto Clothing { get; set; }

        public ItemStatsDto Toys_Games{ get; set; }

        private readonly IStatisticsDataAccess _statisticsDataAccess;

		private readonly IStatisticsContainer _statisticsContainer;
		public CEOModel(IStatisticsDataAccess statisticsDataAccess, IStatisticsContainer statisticsContainer )
        {
			_statisticsDataAccess = statisticsDataAccess;  
			_statisticsContainer = statisticsContainer;
        }

		public double AttendancePercentage { get; private set; }

		public void OnGet()
		{
           

            Electronics = _statisticsContainer.GetItemStatsDto("Electronics");
			Furniture = _statisticsContainer.GetItemStatsDto("Furniture");
			Gaming = _statisticsContainer.GetItemStatsDto("Gaming");
            Kitchen = _statisticsContainer.GetItemStatsDto("Kitchen");
			Office_Supplies = _statisticsContainer.GetItemStatsDto("Office Supplies");
			Sports_outdoors = _statisticsContainer.GetItemStatsDto("Sports & outdoors");
            Clothing = _statisticsContainer.GetItemStatsDto("Clothing");
			Toys_Games = _statisticsContainer.GetItemStatsDto("Toys & Games");

            Categories = _statisticsContainer.GetCategories();

            AttendancePercentage = _statisticsDataAccess.ShowShiftAttendance();
		}
	}
}

EmployeeWebsite/Pages/CreateWeeklyTemplate.cshtml.cs
using MediaBazar.BusinessLogic.Classes;
using MediaBazar.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using static MediaBazar.BusinessLogic.Classes.MyEnums;

namespace EmployeeWebsite.Pages
{
    [Authorize]
    public class CreateWeeklyTemplateModel : PageModel
    {
        private readonly IEmployeeContainer _employeeContainer;
        [BindProperty]
        public ShiftTypes MondayShift { get; set; }

        [BindProperty]
        public ShiftTypes TuesdayShift { get; set; }

        [BindProperty]
        public ShiftTypes WednesdayShift { get; set; }

        [BindProperty]
        public ShiftTypes ThursdayShift { get; set; }

        [BindProperty]
        public ShiftTypes FridayShift { get; set; }

        [BindProperty]
        public ShiftTypes SaturdayShift { get; set; }

        [BindProperty]
        public ShiftTypes SundayShift { get; set; }
        public bool IsEditing { get; set; }
        public Employee Emp { get; set; }
        public Dictionary<DayOfWeek, ShiftTypes>? Preferences { get; set; }
        public CreateWeeklyTemplateModel(IEmployeeContainer employeeContainer)
        {
            _employeeContainer = employeeContainer;
            Preferences= new Dictionary<DayOfWeek, ShiftTypes>();
        }
        public IActionResult OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var empBsnClaim = claimsIdentity.FindFirst("empBsn");

            if (empBsnClaim == null || !int.TryParse(empBsnClaim.Value, out int bsn))
            {
                return Unauthorized();
            }
            Emp = _employeeContainer.GetEmployeeByBcn(bsn);
            Preferences = Emp.Preferences;

            if (Emp == null)
            {
                return NotFound();
            }

            return Page();
        }
        public IActionResult OnPostSavePreferences()
        {
            IsEditing = false;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var empBsnClaim = claimsIdentity.FindFirst("empBsn");
            int bsn = int.Parse(empBsnClaim.Value);

            Emp = _employeeContainer.GetEmployeeByBcn(bsn);

            Preferences.Add(DayOfWeek.Monday, MondayShift);
            Preferences.Add(DayOfWeek.Tuesday, TuesdayShift);
            Preferences.Add(DayOfWeek.Wednesday, WednesdayShift);
            Preferences.Add(DayOfWeek.Thursday, ThursdayShift);
            Preferences.Add(DayOfWeek.Friday, FridayShift);
            Preferences.Add(DayOfWeek.Saturday, SaturdayShift);
            Preferences.Add(DayOfWeek.Sunday, SundayShift);

            if (Emp.Preferences.Count == 0)
            {
                _employeeContainer.WriteShiftPreference(bsn, Preferences);
                return RedirectToPage("CreateWeeklyTemplate");
            }


            _employeeContainer.UpdateShiftPreference(int.Parse(empBsnClaim.Value), Preferences);
            return RedirectToPage("CreateWeeklyTemplate");
        }
        public IActionResult OnPostEnableEditing()
        {
            IsEditing = true;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var empBsnClaim = claimsIdentity.FindFirst("empBsn");
            Emp = _employeeContainer.GetEmployeeByBcn(int.Parse(empBsnClaim.Value));
            Preferences = Emp.Preferences;
            return Page();
        }
    }
}

EmployeeWebsite/Pages/EditEmpInfo.cshtml.cs
using MediaBazar.BusinessLogic.Classes;
using MediaBazar.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmployeeWebsite.Pages
{
    public class EditEmpInfoModel : PageModel
    {
        IEmployeeContainer _employeeContainer;
        public Employee Emp { get; set; }
        [BindProperty]
        public string? FirstName { get; set; }
        [BindProperty]
        public string? LastName { get; set; }
        [BindProperty]
        public string? Address { get; set; }
        [BindProperty]
        public string? TelNumber { get; set; }

        public void OnGet(int bsn)
        {
            Emp = _employeeContainer.GetEmployeeByBcn(bsn);
        }

        public EditEmpInfoModel(IEmployeeContainer employeeContainer)
        {
            _employeeContainer = employeeContainer;
        }

        public IActionResult OnPost(int bsn)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Page();
            }

            Emp = _employeeContainer.GetEmployeeByBcn(bsn);

            if (!string.IsNullOrEmpty(FirstName))
            {
                Emp.FirstName = FirstName;
                _employeeContainer.UpdateEmployeeFirstName(Emp, FirstName);
            }

            if (!string.IsNullOrEmpty(LastName))
            {
                Emp.LastName = LastName;
                _employeeContainer.UpdateEmployeeLastName(Emp, LastName);
            }

            if (!string.IsNullOrEmpty(Address))
            {
                Emp.Address = Address;
                _employeeContainer.UpdateEmployeeAddress(Emp, Address);
            }

            if (!string.IsNullOrEmpty(TelNumber))
            {
                Emp.TelNumber = TelNumber;
                _employeeContainer.UpdateEmployeeTelNumber(Emp, TelNumber);
            }

            return RedirectToPage("Employee", new { bsn = Emp.BSN });
        }
    }
}

EmployeeWebsite/Pages/Employee.cshtml.cs
using MediaBazar.BusinessLogic.Classes;
using MediaBazar.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections;
using System.Globalization;

namespace EmployeeWebsite.Pages
{
    [Authorize]
    public class EmployeeModel : PageModel
    {
        IEmployeeContainer _employeeContainer;

        public Employee Emp { get; set; }

        public bool IsEditMode { get; set; }
        public List<Employee> Emps { get; set; }

        [BindProperty]
        public SickLeaveViewModel SickLeaveViewModel { get; set; }
        [BindProperty]
        public ShiftPreferenceViewModel ShiftPreferenceViewModel { get; set; }
        [BindProperty]
        public string? ErrorMessage { get; set; }
        [BindProperty]
        public bool SetYearlyPreference { get; set; }

        public EmployeeModel(IEmployeeContainer employeeContainer) 
        {
            _employeeContainer = employeeContainer;
        }  
         
        

        public IActionResult OnGet(int bsn)
        {
   
            var user = HttpContext.User;

            
            var bsnClaim = user.FindFirst("empBsn");

            if (bsnClaim != null )
            {
                int empBsn = Convert.ToInt32(bsnClaim.Value);
                Emp = _employeeContainer.GetEmployeeByBcn(empBsn);
                return Page();
            }
            else
            {
                return Forbid();
            }
        }
        
       

        public void OnPost(int bsn, int shiftAtIndex)
        {
            Emp = _employeeContainer.GetEmployeeByBcn(bsn);
            Emp.ShiftsDates[shiftAtIndex].AttendedShift = true;
            
            _employeeContainer.UpdateEmpShift(Emp);


        }



        public async Task<IActionResult> OnPostAssignSickLeaveAsync(int bsn)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Page();
            }

            Emp = _employeeContainer.GetEmployeeByBcn(bsn);

            if (Emp == null)
            {
                return NotFound();
            }

            var startDate = SickLeaveViewModel.StartDate.Date;
            var endDate = SickLeaveViewModel.EndDate.Date;

            if (endDate < startDate)
            {
                ModelState.AddModelError("", "End date must be greater than or equal to start date.");
                return Page();
            }

            if (Emp.SickLeaves == null)
            {
                Emp.SickLeaves = new List<SickLeave>();
            }

            var overlappingSickLeaves = Emp.SickLeaves
                .Where(sl => sl.IsScheduled && ((startDate >= sl.StartDate && startDate <= sl.EndDate) || (endDate >= sl.StartDate && endDate <= sl.EndDate)))
                .ToList();

            if (overlappingSickLeaves.Count > 0)
            {
                ModelState.AddModelError("", "Sick leave overlaps with an existing sick leave.");
                ErrorMessage = "Sick leave overlaps with an existing sick leave.";
                return Page();
            }

            // Create a new SickLeave object from the SickLeaveViewModel
            SickLeave sickLeave = new SickLeave
            {
                StartDate = SickLeaveViewModel.StartDate,
                EndDate = SickLeaveViewModel.EndDate,
                Reason = SickLeaveViewModel.Reason,
                IsScheduled = SickLeaveViewModel.IsScheduled
            };

            Emp.SickLeaves.Add(sickLeave);
            _employeeContainer.UpdateEmpSickLeave(Emp, sickLeave);

            return RedirectToPage("./Employee", new { bsn = Emp.BSN });
        }

        public IActionResult OnPostCreateShiftPreference(int bsn)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Page();
            }
            Emp = _employeeContainer.GetEmployeeByBcn(bsn);

            if (!SetYearlyPreference)
            {
                ShiftPreference shiftPreference = new ShiftPreference
                {
                    Year = ShiftPreferenceViewModel.Year,
                    Month = (int)ShiftPreferenceViewModel.Month,
                    Preference = ShiftPreferenceViewModel.Preference
                };


                Emp.ShiftPreferences.Add(shiftPreference);
                try
                {
                    _employeeContainer.AddShiftPreference(Emp, shiftPreference);
                }
                catch (Exception ex)
                {
                    ErrorMessage = ex.Message;
                    return Page();

                }

                return RedirectToPage(new { bsn = Emp.BSN });
            }
            else
            {
                foreach (var month in CultureInfo.CurrentCulture.DateTimeFormat.MonthNames.Skip(1))
                {
                    int monthIndex = Array.IndexOf(CultureInfo.CurrentCulture.DateTimeFormat.MonthNames, month);
                    ShiftPreference shiftPreference = new ShiftPreference
                    {
                        Year = ShiftPreferenceViewModel.Year,
                        Month = monthIndex,
                        Preference = ShiftPreferenceViewModel.Preference
                    };
                    Emp.ShiftPreferences.Add(shiftPreference);
                    try
                    {
                        _employeeContainer.AddShiftPreference(Emp, shiftPreference);
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = ex.Message;
                        return Page();
                    }
                }
                return RedirectToPage(new { bsn = Emp.BSN });
            }

        }
    }
}

EmployeeWebsite/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace EmployeeWebsite.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

EmployeeWebsite/Pages/Index.cshtml.cs
using MediaBazar.BusinessLogic.Classes;
using MediaBazar.BusinessLogic.Containers;
using MediaBazar.BusinessLogic.Interfaces;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Data.SqlClient;
using System.Reflection;
using System.Security.Claims;

namespace EmployeeWebsite.Pages
{
	public class IndexModel : PageModel
	{
        public List<Employee> Employees { get; set; }
        IEmployeeContainer _employeeContainer;
        public Employee Employee { get; set; }
        private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger, IEmployeeContainer employeeContainer)
        {
			_logger = logger;
            _employeeContainer = employeeContainer;
            Employees = _employeeContainer.LoadEmployees();
		}

		public void OnGet()
		{
            //DataBaseManager database = new DataBaseManager();
            
		}
     
        public IActionResult OnPost(string username, int bsn)
        {
             Employee = _employeeContainer.GetEmployeeByBcn(bsn);
            if (Employee.IsAccountActive == false)
            {
                return Page();
            }
            if (CheckLogin(username, bsn))
            {

                var claims = new List<Claim>
                 {
                     new Claim("empBsn", Employee.BSN.ToString())
                 };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToPage("/Employee", new { bsn = bsn });
            }
            else
            {
                ViewData["ErrorMessage"] = "Invalid username or password.";
                return Page();
            }
            // Perform any necessary logic here

        }



        public bool CheckLogin(string username, int password)
        {
            // Replace the following code with your own logic for checking username and password
            foreach (var emp in Employees)
            {
                if (username == emp.FirstName + " " + emp.LastName && password == emp.BSN)
                {
                    return true;
                }
                //else
                //{
                //    return false;
                //}
            }
            return false;
        }
        //public IActionResult OnPost(string username, int bsn) 
        //{
        //    if (CheckLogin(username, bsn))
        //    {
        //        return RedirectToPage("/Employee");
        //    }
        //    else 
        //    {
        //        ViewData["ErrorMessage"] = "Invalid username or password.";
        //        return Page();
        //    }       
        //}
        //public IActionResult OnPost(string username, int password)
        //{
        //    if (CheckLogin(username, password))
        //    {
        //        // Redirect to the main page if login succeeds
        //        return RedirectToPage("/Employee");
        //    }
        //    else
        //    {
        //        // Show an error message if login fails
        //        TempData["ErrorMessage"] = "Invalid username or password.";
        //        return Page();
        //    }
        //}
    }

   
}

EmployeeWebsite/Pages/CreateWeeklyTemplate.cshtml
@page
@using System.Security.Claims;
@using static MediaBazar.BusinessLogic.Classes.MyEnums;
@model EmployeeWebsite.Pages.CreateWeeklyTemplateModel
@{
    ViewData["Title"] = "Weekly Schedule";

    var claimsIdentity = (ClaimsIdentity)User.Identity;
    var userId = User.Identity.IsAuthenticated ? (User.FindFirstValue("empBsn") ?? string.Empty) : string.Empty;
}

<div class="container">
    <h1>@ViewData["Title"]</h1>

    @if (Model.IsEditing)
    {
        <form method="post">
            <div class="row">
                <div class="col">
                    <div class="square">
                        <label asp-for="MondayShift">Monday</label>
                        <select class="form-control" asp-for="MondayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Monday) && Model.Preferences[DayOfWeek.Monday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Monday) && Model.Preferences[DayOfWeek.Monday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Monday) && Model.Preferences[DayOfWeek.Monday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="TuesdayShift">Tuesday</label>
                        <select class="form-control" asp-for="TuesdayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Tuesday) && Model.Preferences[DayOfWeek.Tuesday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Tuesday) && Model.Preferences[DayOfWeek.Tuesday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Tuesday) && Model.Preferences[DayOfWeek.Tuesday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="WednesdayShift">Wednesday</label>
                        <select class="form-control" asp-for="WednesdayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Wednesday) && Model.Preferences[DayOfWeek.Wednesday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Wednesday) && Model.Preferences[DayOfWeek.Wednesday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Wednesday) && Model.Preferences[DayOfWeek.Wednesday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="ThursdayShift">Thursday</label>
                        <select class="form-control" asp-for="ThursdayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Thursday) && Model.Preferences[DayOfWeek.Thursday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Thursday) && Model.Preferences[DayOfWeek.Thursday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Thursday) && Model.Preferences[DayOfWeek.Thursday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="FridayShift">Friday</label>
                        <select class="form-control" asp-for="FridayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Friday) && Model.Preferences[DayOfWeek.Friday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Friday) && Model.Preferences[DayOfWeek.Friday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Friday) && Model.Preferences[DayOfWeek.Friday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="SaturdayShift">Saturday</label>
                        <select class="form-control" asp-for="SaturdayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Saturday) && Model.Preferences[DayOfWeek.Saturday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Saturday) && Model.Preferences[DayOfWeek.Saturday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Saturday) && Model.Preferences[DayOfWeek.Saturday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="square">
                        <label asp-for="SundayShift">Sunday</label>
                        <select class="form-control" asp-for="SundayShift">
                            <option value="MORNING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Sunday) && Model.Preferences[DayOfWeek.Sunday] == ShiftTypes.MORNING)">Morning</option>
                            <option value="EVENING" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Sunday) && Model.Preferences[DayOfWeek.Sunday] == ShiftTypes.EVENING)">Evening</option>
                            <option value="NIGHT" selected="@(Model.Preferences.ContainsKey(DayOfWeek.Sunday) && Model.Preferences[DayOfWeek.Sunday] == ShiftTypes.NIGHT)">Night</option>
                        </select>
                    </div>
                </div>
            </div>
                   <button type="submit" asp-page-handler="SavePreferences" class="btn-primary" >Save Preferences</button>
        </form>
    }else
    {
        <form method="post">
                 <div class="row">
                      <div class="col">
                        <div class="square">
                    <p><strong>Shift Preferences:</strong></p>
                                    <p><strong>Monday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Monday, out var mondayShift) ? mondayShift.ToString() : string.Empty)</strong></p>
                        </div>
                        </div>

                        <div class="col">
                      <div class="square">
                    <p><strong>Shift Preferences:</strong></p>
                                    <p><strong>Tuesday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Tuesday, out var tuesdayShift) ? tuesdayShift.ToString() : string.Empty)</strong></p>
                        </div>
                        </div>
                        <div class="col">
                        <div class="square">
                            <p><strong>Shift Preferences:</strong></p>
                                    <p><strong>Wednesday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Wednesday, out var wednesdayShift) ? wednesdayShift.ToString() : string.Empty)</strong></p>
                        </div>
                        </div>

                            <div class="col">
                        <div class="square">
                            <p><strong>Shift Preferences:</strong></p>
                                    <p><strong>Thursday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Thursday, out var thursdayShift) ? thursdayShift.ToString() : string.Empty)</strong></p>
                        </div>
                            </div>

                            <div class="col">
                        <div class="square">
                            <p><strong>Shift Preferences:</strong></p>
                                    <p><strong>Friday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Friday, out var fridayShift) ? fridayShift.ToString() : string.Empty)</strong></p>
                        </div>
                        </div>
                          

                             <div class="col">
                        <div class="square">
                                <p><strong>Shift Preferences:</strong></p>
                                <p><strong>Saturday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Saturday, out var saturdayShift) ? saturdayShift.ToString() : string.Empty)</strong></p>
                       </div>
                               </div>

                            <div class="col">
                        <div class="square">
                                <p><strong>Shift Preferences:</strong></p>
                                <p><strong>Sunday: @(Model.Emp.Preferences.TryGetValue(DayOfWeek.Sunday, out var sundayShift) ? sundayShift.ToString() : string.Empty)</strong></p>
                        </div>
                            </div>

                </div>
            
            <button type="submit" class="btn-primary" asp-page-handler="EnableEditing">Edit Preference</button>
        </form>
    }
    

EmployeeWebsite/Pages/EditEmpInfo.cshtml
@page
@model EmployeeWebsite.Pages.EditEmpInfoModel
@{
}

<div class="card mb-4">
    <div class="card-body">
        <div class="row">
            <div class="mb-3">
                <form method="post">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control">
                <span asp-validation-for="FirstName" class="text-danger"></span>

                 <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control">
                <span asp-validation-for="LastName" class="text-danger"></span>

                <label asp-for="TelNumber" class="form-label"></label>
                <input asp-for="TelNumber" class="form-control">
                <span asp-validation-for="TelNumber" class="text-danger"></span>

                <label asp-for="Address" class="form-label"></label>
                <input asp-for="Address" class="form-control">
                <span asp-validation-for="Address" class="text-danger"></span>

                <button class="btn btn-primary btn-lg" type="submit" asp-page-handler="AddToCart"  asp-route-bsn="@Model.Emp.BSN">
                    Update Info</button>
                </form>
            </div>
        </div>
    </div>
</div>

EmployeeWebsite/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Media Bazaar Employee Scheduling System";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-8 col-xs-12">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="text-center">@ViewData["Title"]</h1>
                    <hr />
                    <form method="post">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" asp-for="Employee.FirstName" class="form-control" required />
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="bsn" asp-for="Employee.BSN" class="form-control" required />
                        </div>
                          <div class="form-group text-center">
                            <input type="submit" class="btn btn-primary btn-lg" value="Log-in"></<input>
                          </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>